{
 "title": "PostgreSQL Exporter Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values({\"pg_stat_database_xact_commit, datname\"},$database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Reads/sec",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit[5m]) / (rate(pg_stat_database_blks_read[5m]) + rate(pg_stat_database_blks_hit[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "bargauge",
   "description": "DB Size (GB)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple Operations",
   "type": "timeseries",
   "description": "Tuples inserted/sec | Tuples updated/sec | Tuples deleted/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction ThroughPut",
   "type": "timeseries",
   "description": "Commits/sec | Rollbacks/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"postgres\"}[5m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "timeseries",
   "description": "Active Connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exporter",
   "type": "gauge",
   "description": "Exporter UP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  }
 ]
}